language: php

sudo: false

php:
  - 7.0
  - 7.0snapshot
  - 7.1
  - 7.1snapshot
  - 7.2
  - 7.2snapshot
  - master

before_script:
  - composer self-update
  - composer clear-cache
  - composer install --no-interaction

script:
  - vendor/bin/phpcs src test
  - vendor/bin/phpstan analyse --no-progress --level=max src test
  - php vendor/phpunit/phpunit/phpunit --configuration phpunit.xml

notifications:
    email: false
